# Jekyll configuration file for Jiaheng Xiong's academic homepage

# Site Settings
title: "Jiaheng Xiong"
description: "PhD student at Politecnico di Milano working on optical and quantum networks."
repository: "jiahengxiong/jiahengxiong.github.io"
google_scholar_stats_use_cdn: true

# Google Analytics (optional)
google_analytics_id:

# SEO Related (optional)
google_site_verification:
bing_site_verification:
baidu_site_verification:

# Site Author
author:
  name: "Jiaheng Xiong"
  avatar: "images/android-chrome-512x512.png"
  bio: "PhD student at Politecnico di Milano"
  location: "Milan, Italy"
  employer: "Politecnico di Milano"
  pubmed:
  googlescholar: "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID"
  email: "jiaheng.xiong@polimi.it"
  researchgate:
  uri:
  github: "jiahengxiong"
  linkedin: "jiahengxiong"
  dblp:
  orcid:
  stackoverflow:
  twitter:

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
